replicaCount: 1

image:
  repository: image-build-controller  # Required: e.g. harbor.example.com/brewery/imagebuild-controller
  tag: 0.0.1         # Defaults to Chart.appVersion
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}

# Install CRD with chart
installCrd: true

# Application configuration
config:
  dockerizer:
    kubernetes:
      verifySsl: false
      kubeConfig:
        mode: IN_CLUSTER
    imagebuild:
      kanikoImage: gcr.io/kaniko-project/executor:latest
