spring:
  application:
    name: dockerizer-controller

dockerizer:
  kubernetes:
    verify-ssl: false
    kube-config:
      mode: FILE
      kube-config-path: ${HOME}/.kube/config
  imagebuild:
    kaniko-image: gcr.io/kaniko-project/executor:v1.24.0
