{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.postgresql.enabled (not .Values.config.datasource.username) }}
  spring.datasource.username: {{ .Values.postgresql.auth.username | quote }}
  spring.datasource.password: {{ .Values.postgresql.auth.password | quote }}
  {{- else }}
  spring.datasource.username: {{ .Values.config.datasource.username | quote }}
  spring.datasource.password: {{ .Values.config.datasource.password | quote }}
  {{- end }}
  {{- if and .Values.config.dockerizer.registry.ngc.enabled .Values.config.dockerizer.registry.ngc.apiKey }}
  ngc-api-key: {{ .Values.config.dockerizer.registry.ngc.apiKey | quote }}
  {{- end }}
{{- end }}
