apiVersion: v2
name: dockerizer-backend
description: Dockerizer Backend Server - REST API for Dockerfile management and ImageBuild CR creation
type: application
version: 0.1.0
appVersion: "0.0.1-SNAPSHOT"
