replicaCount: 1

image:
  repository: ""  # ## HELM installer ##
  pullPolicy: Always
  tag: ""  # ## HELM installer ##

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations:
  ad.datadoghq.com/dockerizer-backend.logs: '[{"source": "java", "service": "dockerizer-backend"}]'
podLabels: {}

podSecurityContext: {}

securityContext: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - name: ca-certs
    secret:
      secretName: custom-ca-certs

volumeMounts:
  - mountPath: /certificates
    name: ca-certs
    readOnly: true

nodeSelector: {}

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

envFrom:
  configMapSuffix: envs
  secretSuffix: envs

applicationYaml:
  server:
    port: &serverPort 8080
  spring:
    profiles:
      active: prod
    datasource:
      url: "jdbc:postgresql://harbor-database.aipub.svc.cluster.local:5432/dockerizer"
      username: "aipub"
      password: ""  # ## HELM installer ##
      driverClassName: org.postgresql.Driver
    jpa:
      ddlAuto: validate
      showSql: false
  dockerizer:
    kubernetes:
      verifySsl: true
      kubeConfig:
        mode: IN_CLUSTER
    dockerfile:
      forbiddenInstructions:
        - ADD
    volume:
      clientMode: K8S
      proxyBaseUrl: ""
    registry:
      ngc:
        enabled: false
        catalogUrl: https://api.ngc.nvidia.com/v2
        registryUrl: https://nvcr.io
        apiKey: ""
      huggingface:
        enabled: false
        dockerHubUrl: https://hub.docker.com/v2
        namespace: huggingface
  logging:
    level:
      dockerizer: ""  # ## HELM installer ##
  management:
    server:
      port: &managementPort 8082
    endpoint:
      health:
        probes:
          enabled: true
    endpoints:
      web:
        exposure:
          include: health
    health:
      livenessstate:
        enabled: true
      readinessstate:
        enabled: true

agent:
  datadog: "false"
  javaToolOptions: "-javaagent:/opt/aipub/agents/dd-java-agent.jar"
  ddTraceAgentPort: "8126"
  ddService: "dockerizer-backend"
  ddEnv: "production"
  ddVersion: "1.0.0"
  host: "aipub-backend-datadog.aipub.svc.cluster.local"
  ddProfilingEnabled: "true"
  ddProfilingAllocationEnabled: "true"

service:
  type: ClusterIP
  ports:
    - name: http
      port: *serverPort
      protocol: TCP
      targetPort: *serverPort
    - name: management
      port: *managementPort
      protocol: TCP
      targetPort: *managementPort

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: *managementPort
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: *managementPort
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

ingress:
  enabled: true
  className: "cilium"
  annotations: {}
  hosts:
    - host: ""  # ## HELM installer ##
  frontend:
    serviceName: dockerizer-web
    servicePort: 80
  tls: []
