apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "imagebuild-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imagebuild-controller.labels" . | nindent 4 }}
data:
  application.yaml: |
    spring:
      application:
        name: dockerizer-controller

    dockerizer:
      kubernetes:
        verify-ssl: {{ .Values.config.dockerizer.kubernetes.verifySsl }}
        kube-config:
          mode: {{ .Values.config.dockerizer.kubernetes.kubeConfig.mode }}
      imagebuild:
        kaniko-image: {{ .Values.config.dockerizer.imagebuild.kanikoImage }}
